server:
  port: 9090

spring:
  profiles:
    active: prod
  application:
    name: facade-h5-application
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml